[server]
enableStaticServing = true

[theme]

# Primary accent for interactive elements
primaryColor="#cc0033"

# Background color for the main content area
backgroundColor="#fafafa"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#AEB3B7"

# Color used for almost all text
textColor="#313131"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[mapbox]
token = 'pk.eyJ1IjoicGxhbmFqaCIsImEiOiJjbG4wZm13M3cxc3JuMmtvNjE1NHJod3c3In0.-0dZNNgm1JvpFcjlp65z3Q'